name: Deploy build

on:
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Compile proposal narrative and summary LaTeX
      uses: docker://xucheng/texlive-full:latest
      with:
        entrypoint: /bin/sh
        args: |
          -c "\
          apk --no-cache add make && \
          make document"
    - name: List directory contents
      run: ls -lhtra
    - name: Setup build for deployment
      run: |
        mkdir -p docs/_build
        cp CHEP_2021_proposal.pdf docs/_build/CHEP_2021_proposal.pdf
    - name: Deploy build to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
